---
# vars file for ec2_lauch/
aws_access_key: '<Your access key>'
aws_secret_key: '<Your secret key>'

vpc_title: 'k8s Cluster'
vpc_name: "{{ vpc_title }} VPC"
igw_name: "{{ vpc_title }} IGW"
subnet_name: "{{ vpc_title }} Subnet"
security_group_name: "{{ vpc_title }} Security Group"
route_table_name: "{{ vpc_title }} route table"
vpcCidrBlock: '10.0.0.0/16'
subNetCidrBlock: '10.0.1.0/24'
port22CidrBlock: '0.0.0.0/0'
destinationCidrBlock: '0.0.0.0/0'
state: "present"
zone: "ap-south-1a"
region: "ap-south-1"
OS_names:
     - "k8s_Master"
     - "k8s_Slave1"
     - "k8s_Slave2"
